### ISSUE TITLE
Cant get sign data

### ISSUE THREAD

**Issue by luanon404** [riyadmondol2006/Android-Signature-And-Integrity-Check-Bypass#3]
App link: https://apkcombo.com/vi/lucky-coin-earn-real-cash/com.luckycoin.earn.realcash.app/download/apk

Error:
`Exception in thread "main" java.lang.IllegalAccessError: class anymy.sign.BinSignatureFix (in unnamed module @0x32a2b372) cannot access class sun.security.pkcs.PKCS7 (in module java.base) because module java.base does not export sun.security.pkcs to unnamed module @0x32a2b372
        at anymy.sign.BinSignatureFix.getApkSignatureData(Unknown Source)
        at anymy.sign.BinSignatureFix.BinSignatureFix(Unknown Source)
        at anymy.sign.BinSignatureFix.main(Unknown Source)`

Im using wsl with latest update 22.04

**Comment by riyadmondol2006** [comment]
is it windows?

**Comment by luanon404** [comment]
yes

**Comment by riyadmondol2006** [comment]
Can you try with WSL?
or old java version
wsl suggested

**Comment by luanon404** [comment]
which version? jre 8 11 17 18 19?

**Comment by luanon404** [comment]
i think i will try with termux

**Comment by riyadmondol2006** [comment]
yes if you are trying with termux you might see the .dex file

**Comment by luanon404** [comment]
where i can find apksigner.jar? i see it in your video but i dont see in release

**Comment by riyadmondol2006** [comment]
Sign using mt Manager or just google sign android apk

**Comment by riyadmondol2006** [comment]
any more questions or i close the issue?

**Comment by luanon404** [comment]
how, can u send me a video ?

**Comment by riyadmondol2006** [comment]
about?

**Comment by luanon404** [comment]
mt manager
