### ISSUE TITLE
Difference between APKKiller and this?

### ISSUE THREAD

**Issue by ghost** [riyadmondol2006/Android-Signature-And-Integrity-Check-Bypass#4]
What is the benefit of using Java side only compared to cpp side of APKKiller? Is this a better Java implemention that would work with more games?

**Comment by riyadmondol2006** [comment]
i haven't compare if you can say i can add it in readme

**Comment by ghost** [comment]
Oh, I was just wondering 😅

**Comment by ghost** [comment]
I read it as APKKiller instead ApkSignatureKiller, my bad
