### ISSUE TITLE
Game still crashes

### ISSUE THREAD

**Issue by ghost** [riyadmondol2006/Android-Signature-And-Integrity-Check-Bypass#5]
it seems signature bypass is not working, the game crashes if signed no matter if signature bypass is called. I'm sure I did everything right, added sign hash and add call in OnCreate (there was no attachBaseContext)

The game: https://apkcombo.com/%E3%82%AF%E3%83%A9%E3%83%83%E3%82%B7%E3%83%A5%E3%83%95%E3%82%A3%E3%83%BC%E3%83%90%E3%83%BC-%E3%83%91%E3%82%BA%E3%83%ABrpg-%E6%96%B0%E6%84%9F%E8%A6%9A%E3%83%96%E3%83%83%E5%A3%8A%E3%81%97%E3%83%90%E3%83%88%E3%83%AB/jp.wonderplanet.CrashFever/

**Comment by riyadmondol2006** [comment]
it has a powerful sign check use cnfix 3.7+

**Comment by ghost** [comment]
> it has a powerful sign check use cnfix 3.7+

Can you send me apk? I can only find 3.3

**Comment by ghost** [comment]
https://github.com/L-JINBIN/ApkSignatureKiller worked perfectly so it appears this new sig killer is broken
